# Centos based container with Java, Maven, Ant, Git and Tomcat
FROM scratch
ADD centos-7-x86_64-docker.tar.xz /

LABEL \
    org.label-schema.schema-version="1.0" \
    org.label-schema.name="CentOS Base Image" \
    org.label-schema.vendor="CentOS" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20200504" \
    org.opencontainers.image.title="CentOS Base Image" \
    org.opencontainers.image.vendor="CentOS" \
    org.opencontainers.image.licenses="GPL-2.0-only" \
    org.opencontainers.image.created="2020-05-04 00:00:00+01:00"

#Local variables to build this docker
ARG TOMCAT_MAJOR_VERSION=7
ARG TOMCAT_MINOR_VERSION=7.0.86
ARG ANT_VERSION=1.10.3
ARG MAVEN_VERSION=3.3.9
ARG USER_HOME_DIR="/root"
ARG SHA=b52956373fab1dd4277926507ab189fb797b3bc51a2a267a193c931fffad8408
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

#Environment variables apply to the docker image
ENV JAVA_HOME /usr/lib/jvm/java-openjdk
ENV CATALINA_HOME /opt/tomcat 
ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin:$CATALINA_HOME/scripts
ENV JAVA_OPTS -Dlog.location=/opt/tomcat/logs -Dusers.loc=/opt/tomcat/conf -Xms1g -Xmx2g
ENV MAVEN_OPTS -Xms256m -Xmx1g
#ENV lmEnv fitnesse_A_cpstest
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
ENV MVNENV local
#ENV MVNPROFILE shortcycle

# Install prepare infrastructure
RUN yum -y update && \
yum -y install wget && \
yum -y install tar

# Install open JDK
RUN yum -y install java-1.8.0-openjdk-devel && rm -rf /var/cache/yum

#Install maven
RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

#Installing_Tomcat7
RUN wget http://mirrors.sorengard.com/apache/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz \
  && tar xvzf apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz \
  && mv apache-tomcat-${TOMCAT_MINOR_VERSION} /opt/tomcat

#Installing_Ant
RUN wget http://apache.mirrors.tds.net//ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
  && tar xvzf apache-ant-${ANT_VERSION}-bin.tar.gz \
  && mv apache-ant-${ANT_VERSION} /opt/ant

#Install GIT
RUN yum -y install git

EXPOSE 9910
