# Centos based container with Java, Maven, Ant, Git and Tomcat FROM devopsgurus:v1 RUN git clone https://TheDevopsGurus:devops2020@github.com/TheDevopsGurus/HelloWorld.git RUN gradle build
FROM centos:7

#Local variables to build this docker
ARG USER_HOME_DIR="/root"
ARG SHA=b52956373fab1dd4277926507ab189fb797b3bc51a2a267a193c931fffad8408

#Environment variables apply to the docker image
ENV JAVA_HOME /usr/lib/jvm/java-openjdk
ENV PATH $PATH:$JAVA_HOME/bin

# Install prepare infrastructure
RUN yum -y update && \
yum -y install wget && \
yum -y install tar && \
yum -y install unzip

# Install open JDK
RUN yum -y install java-1.8.0-openjdk-devel && rm -rf /var/cache/yum

#Install gradle
RUN wget https://services.gradle.org/distributions/gradle-3.5-bin.zip -P /tmp
RUN unzip -d /opt/gradle /tmp/gradle-*.zip


#Install GIT
RUN yum -y install git

EXPOSE 9910

