pipeline {
   agent any

   tools {
      // Install the Maven version configured as "M3" and add it to the path.
      gradle "myGradle"

   }

   stages {
      stage('Build') {
         steps {
            sh "java -version"
            
            sh "docker build -t devopsgurus:v1 -f DockerFile ."
            
         }

           }
   }
}
