pipeline {
   agent any

   

   stages {
      stage('Build') {
         steps {
            sh "java -version"
            sh "docker build -t devopsgurus:v1 -f ./Docker/DockerFile ."
            
         }

           }
   }
}
